name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0  # Si vous en avez besoin
  font_awesome_flutter: ^10.1.0  # Ajoutez cette ligne pour FontAwesome avec null safety


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Vous pouvez toujours ajouter des images à votre projet ici
